### ISSUE TITLE
Consturir pdf y publicarlo en Github Pages

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/tfg#1]
## Descripción

Para que el tutor pueda ver los diferentes MVP, es necesario tener un mecanismo para crear/hacer releases de MVP, que genere un PDF.

## Scope

- Permite crear releases manuales de forma sencilla.

Historia de usuario: #33.

**Comment by JJ** [comment]
@antoniogamiz No deberías meter PDFs en el repo, sólo en los releases. Y en ese caso, deberías cambiarlo por "cada vez que hago un tag". Hacer un build de latex también tarda un mogollón, así que tampoco es cuestión de que lo ejecutes cada vez

**Comment by antoniogamiz** [comment]
Mm, vale. Estoy al tanto de que no se pueden subir pdfs, aunque me suelo saltar esa regla cuando los pushs son a `gh-pages` porque normalmente hago un reset de esa rama para dejar un solo commit (porque no me interesa preservar la historia de commits). Por esa razón, la principal desventaja de usar binarios en git, deja de estar.

**Comment by JJ** [comment]
Sigue teniendo el problema de ocupar un montón de espacio, y de no usar
realmente ninguna ventaja de git al ser binario.

**Comment by antoniogamiz** [comment]
Lo del espacio es cierto, lo de git da un poco más igual porque al usar la
rama gh-pages las ventajas de git no me hacen falta. La desventaja que le
veo a lo de la release es que no hay una URL donde puedas consultar el
estado último del proyecto.

**Comment by JJ** [comment]
Puedes generarla automáticamente. Mira https://github.com/JJ/cv

**Comment by antoniogamiz** [comment]
Pero en ese repositorio te tienes que descargar el PDF. Mi preferencia es
que no tengas que hacerlo. Según tengo entendido los enlaces de las
releases te descargan el archivo en lugar de abrirlo, ¿No? Maybe estoy
equivocado.

**Comment by JJ** [comment]
El mar, 12 oct 2021 a las 18:09, Antonio ***@***.***>)
escribió:

> Pero en ese repositorio te tienes que descargar el PDF. Mi preferencia es
> que no tengas que hacerlo. Según tengo entendido los enlaces de las
> releases te descargan el archivo en lugar de abrirlo, ¿No? Maybe estoy
> equivocado.
>

No tiene nada que ver con el enlace. Tendrá que ver con el servidor web, y
el navegador.

**Comment by antoniogamiz** [comment]
Creo que Github le añade el metadata `download` al element html `a` de los
enlaces de las releases, por eso se descarga cuando le das
independientemente del navegador.

**Comment by antoniogamiz** [comment]
Ah pues no, los enlaces de las releases hacen una request a un endpoint en especifico para que se descarguen. Anyway, creo que esa solución sigue siendo independiente del navegador y siempre se van a descargar cuando clickes, a diferencia de una URL proveniente de gh-pages.

**Comment by antoniogamiz** [comment]
Concretamente, ese endpoint manda una response poniendo el `Content-Disposition` a `attachment`, que hace que el navegador lo descargue. [Referencia](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition)

![image](https://user-images.githubusercontent.com/22995015/136993772-b725cfe8-1a5c-4ec6-befa-5c07b6199fde.png)

Todos los días se aprende algo. En resumen, viendo esto, independientemente del navegador, las URLs de archivos adjuntos a las releases van a abrir una pestaña de descarga en lugar de abrir el archivo en modo visualización en una pestaña del navegador.
