### ISSUE TITLE
Los milestones tienen que describir un producto mínimamente viable

### ISSUE THREAD

**Issue by JJ** [antoniogamiz/tfg#31]
Y el actual, [0](https://github.com/antoniogamiz/tfg/milestone/1) simplemente describe una serie de tareas. Un producto mínimamente viable debe incluir también criterios de viabilidad.

**Comment by antoniogamiz** [comment]
@JJ ¿Los criterios de aceptación supongo que deberían aparecer en el trabajo?

**Comment by JJ** [comment]
Viabilidad es más o menos lo mismo que aceptación, sí. Tanto en el informe que presentes del TFG como en el milestone en sí mismo (para referencia)

**Comment by antoniogamiz** [comment]
Este issue forma parte de #34.

**Comment by antoniogamiz** [comment]
Los milestones han sido reescritos así que esta la voy a cerrar manualmente.
