### ISSUE TITLE
[HU0] Descripción de la planificación del proyecto

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/tfg#34]
## Descripción

Como miembro del tribunal/tutor necesito definir y conocer la metodología que se va a usar para realizar el trabajo, sus principales objetivos, usuarios, etc.

Como tutor del trabajo necesito disponer de una forma fácil de leer el resultado final en cada una de las iteraciones.

## Criterio de aceptación

- Objetivos definidos
- Usuarios definidos
- Historias de usuario definidas
- Metodología definida
- Descripción de la planificación del proyecto.
- Poder crear releases de forma sencilla.
- No tener faltas en el proyecto.

**Comment by JJ** [comment]
¿A quién beneficia esto? Principalmente beneficiará a los miembros del tribunal (que son los clientes principales). Conviene que los incluyas también en el HU.
En general, en todo caso, la planificación del proyecto no es un HU. La *descripción* de la misma sí tiene que ser una parte del producto final, que incluirá el informe.
