### ISSUE TITLE
Usar git hook para evitar commitear cosas con faltas de ortografía

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/tfg#40]
## Scope

Como desarrollador se me olvida correr el spell antes de hacer commit. Por lo tanto, creo que es necesario añadir un hook que haga esto por mi automaticámente.

**Comment by JJ** [comment]
No hace falta que uses un hook, pero up to you :-)

**Comment by antoniogamiz** [comment]
@JJ más que nada es por no hacer muchos commits poniendo “typos”

**Comment by JJ** [comment]
@antoniogamiz Como te digo, es un poco indiferente. A mi no me suelen gustar los hooks porque es infraestructura implícita que no puedes replicar sin instrucciones al forkear un repo. Para trabajo en equipo es poco aconsejable. Pero en este caso, es simplemente un "judgment call". Como todas las elecciones en el TFG, tienes que justificarla.
