### ISSUE TITLE
Se debe avanzar en los milestones por orden

### ISSUE THREAD

**Issue by JJ** [antoniogamiz/tfg#44]
Si no, no serían milestones. El milestone 0 tendrá un deliverable, sin el cual no se podrá trabajar en el siguiente, así que ahora hay que priorizar ese milestone antes de ponerse con otro.

**Comment by antoniogamiz** [comment]
Vale, de los últimos comentarios de https://github.com/antoniogamiz/tfg/pull/10 voy a ir cerrando la milestone 0 y a empezar la siguiente (porque por ahora el la milestone 0 es ya MVP, creo yo). En una milestone posterior de revisión final le daré otra vuelta.
