### ISSUE TITLE
Implementar modelo word2vec

### ISSUE THREAD

**Issue by antoniogamiz** [antoniogamiz/tfg#50]
## Scope

Se va a implementar el modelo word2vec desde cero, posteriormente se va a validar que está bien implementado y una vez se confirme se empezará a trabajar sobre la extensión y modificaciones.

- HU: https://github.com/antoniogamiz/tfg/issues/49

**Comment by JJ** [comment]
Deberías plantear aquí cuales son los problemas que plantea este modelo. Que además no será word2vec, sino trope2vec
